// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DailyStats {
    /**
     * Creates a new DailyStats instance.
     * @param {Partial<DailyStats>} [$$source = {}] - The source object to create the DailyStats.
     */
    constructor($$source = {}) {
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("work_secs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["work_secs"] = 0;
        }
        if (!("break_secs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["break_secs"] = 0;
        }
        if (!("breaks" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["breaks"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DailyStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailyStats(/** @type {Partial<DailyStats>} */($$parsedSource));
    }
}

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("work_interval" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["work_interval"] = 0;
        }
        if (!("break_duration" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["break_duration"] = 0;
        }
        if (!("strict_mode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["strict_mode"] = false;
        }
        if (!("sound_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sound_enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const TimerPhase = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    TimerIdle: 0,
    TimerWorking: 1,
    TimerBreak: 2,
    TimerWaiting: 3,
};

export class TimerState {
    /**
     * Creates a new TimerState instance.
     * @param {Partial<TimerState>} [$$source = {}] - The source object to create the TimerState.
     */
    constructor($$source = {}) {
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {TimerPhase}
             */
            this["phase"] = TimerPhase.$zero;
        }
        if (!("elapsed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["elapsed"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("total_work" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_work"] = 0;
        }
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimerState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TimerState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimerState(/** @type {Partial<TimerState>} */($$parsedSource));
    }
}
