// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function Get() {
    return $Call.ByID(3418067286).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(4004070243).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.Settings} st
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(st) {
    return $Call.ByID(1459213882, st);
}

/**
 * @param {$models.Settings} st
 * @returns {$CancellablePromise<void>}
 */
export function Set(st) {
    return $Call.ByID(1506399258, st);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
