// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {number} count
 * @returns {$CancellablePromise<void>}
 */
export function AddBreak(count) {
    return $Call.ByID(1220968698, count);
}

/**
 * @param {number} secs
 * @returns {$CancellablePromise<void>}
 */
export function AddWork(secs) {
    return $Call.ByID(1717854514, secs);
}

/**
 * @param {number} days
 * @returns {$CancellablePromise<$models.DailyStats[]>}
 */
export function GetRecent(days) {
    return $Call.ByID(1357846211, days).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DailyStats | null>}
 */
export function GetToday() {
    return $Call.ByID(1386204217).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DailyStats.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType0);
