// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.TimerState>}
 */
export function GetState() {
    return $Call.ByID(3468478857).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function PauseResume() {
    return $Call.ByID(4234570181);
}

/**
 * RefreshGoals re-reads settings and updates timer targets without restarting.
 * @returns {$CancellablePromise<void>}
 */
export function RefreshGoals() {
    return $Call.ByID(390095325);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowSettings() {
    return $Call.ByID(1428322796);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SkipBreak() {
    return $Call.ByID(2824464530);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(3098818580);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(4061173200);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Toggle() {
    return $Call.ByID(3794877556);
}

// Private type creation functions
const $$createType0 = $models.TimerState.createFrom;
